name: Publish Packages

on:
  push:
    branches: [ sufficit ]    

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-versions: [ '2.2.x' ]
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v1
        
    - name: Install dependencies
      working-directory: ./Asterisk.2013/Asterisk.NET
      run: dotnet restore
      
    - name: Build
      working-directory: ./Asterisk.2013/Asterisk.NET
      run: dotnet build --configuration Packing
      
    - name: Deploy Package 
      working-directory: ./Asterisk.2013/Asterisk.NET
      run: dotnet pack --configuration Packing --output ./nupkgs
    
    - name: Publish to Nuget.Org
      working-directory: ./Asterisk.2013/Asterisk.NET
      run: dotnet nuget push --skip-duplicate ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
      
    - name: Publish to GitHub
      working-directory: ./Asterisk.2013/Asterisk.NET
      run: dotnet nuget push --skip-duplicate ./nupkgs/*.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{github.token}}
     